// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOT1-YxD2gGmsCITlONd_bTVK2Z_FtjU',
    appId: '1:786314174253:web:c05bbe06a4b3d9a606fda4',
    messagingSenderId: '786314174253',
    projectId: 'progressive-jewellery',
    authDomain: 'progressive-jewellery.firebaseapp.com',
    storageBucket: 'progressive-jewellery.firebasestorage.app',
    measurementId: 'G-VKNPF0MHC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcOk9VbDi4EHeUC28pVAfwNtW7nVumux0',
    appId: '1:786314174253:android:2b7424841fc7bfcc06fda4',
    messagingSenderId: '786314174253',
    projectId: 'progressive-jewellery',
    storageBucket: 'progressive-jewellery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoO9AyICvNm3HoEwu_R2hA5VsAxJCVWJU',
    appId: '1:786314174253:ios:19221a941e28fe1b06fda4',
    messagingSenderId: '786314174253',
    projectId: 'progressive-jewellery',
    storageBucket: 'progressive-jewellery.firebasestorage.app',
    iosBundleId: 'com.example.progressiveJewellery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoO9AyICvNm3HoEwu_R2hA5VsAxJCVWJU',
    appId: '1:786314174253:ios:19221a941e28fe1b06fda4',
    messagingSenderId: '786314174253',
    projectId: 'progressive-jewellery',
    storageBucket: 'progressive-jewellery.firebasestorage.app',
    iosBundleId: 'com.example.progressiveJewellery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuOT1-YxD2gGmsCITlONd_bTVK2Z_FtjU',
    appId: '1:786314174253:web:db233eaed9dd37a706fda4',
    messagingSenderId: '786314174253',
    projectId: 'progressive-jewellery',
    authDomain: 'progressive-jewellery.firebaseapp.com',
    storageBucket: 'progressive-jewellery.firebasestorage.app',
    measurementId: 'G-2BCXLQQJRS',
  );
}
